#!/bin/bash
# Pest Control script for operator host commands

case "$OSTYPE" in
  darwin*)
        rootdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
        selfname=$(basename "$(readlink -f "${BASH_SOURCE[0]}")")
        ;;
  *)
        rootdir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
        selfname=$(basename "$(readlink -f "${BASH_SOURCE[0]}")")
        ;;
esac

${rootdir}/pest-op run $*