application:
  defaultClusterId: "cloud-insecure"

  clusters:
    - cluster-id: "cloud-insecure"
      cluster-name: "Local 3-node Cluster (insecure)"
      cluster-type: hosted_insecure
      admin-url: "http://10.6.6.12:8080"
      data-source-properties:
        url: "jdbc:postgresql://10.6.6.12:26257/defaultdb?sslmode=disable"
        username: "root"
        password: ""
      version: "v25.2.2.linux-amd64"
      nodes:
        - url: http://10.6.6.12:9090
          name: n1
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1a"
          advertise-addr: 10.6.6.12:25257
          advertise-proxy-addr: 10.6.6.12:35257
          listen-addr: 10.6.6.12:25257
          sql-addr: 10.6.6.12:26257
          http-addr: 10.6.6.12:8080
        - url: http://10.6.28.206:9090
          name: n2
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1b"
          advertise-addr: 10.6.28.206:25258
          advertise-proxy-addr: 10.6.28.206:35258
          listen-addr: 10.6.28.206:25258
          sql-addr: 10.6.28.206:26258
          http-addr: 10.6.28.206:8081
        - url: http://10.6.38.225:9090
          name: n3
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1c"
          advertise-addr: 10.6.38.225:25259
          advertise-proxy-addr: 10.6.38.225:35259
          listen-addr: 10.6.38.225:25259
          sql-addr: 10.6.38.225:26259
          http-addr: 10.6.38.225:8082
