###############################################################################################################
# Pest Control Application Configuration
#
# This file overrides the application configuration properties mainly by providing a list of available
# CockroachDB clusters for users to pick from at login time. The credentials are used to retrieve Cluster API
# session tokens and provide bearer tokens in case of CockroachDB cloud (Cloud API). The cluster type is used
# to adapt security settings and certain UI features.
#
# See 'src/resources/application.yml' for all other properties or
# https://docs.spring.io/spring-boot/appendix/application-properties/index.html for all spring boot properties.
###############################################################################################################

application:
  ## List of pre-configured CockroachDB clusters
  #
  #  cluster-id: Either a CockroachDB cloud cluster ID any unique ID for other cluster types
  #  cluster-name: Cluster display name
  #  cluster-type: cloud_dedicated|remote_secure|remote_insecure|hosted_secure|hosted_insecure
  #  data-source-properties:
  #    url: The JDBC connection url
  #    username: The SQL user name with ADMIN role (optional)
  #    password: The SQL user password (optional)
  #  admin-url: Base URL for the Cluster API, typically the regional/local cluster load balancer endpoint (optional).
  #
  # For cloud_dedicated type only:
  #  api-key: Required, see https://www.cockroachlabs.com/docs/cockroachcloud/managing-access#create-api-keys
  #
  # For hosted_insecure and hosted_secure types only:
  #  version: (see below)
  #  nodes: (see below)

  clusters:
    - cluster-id: "97a73235-fa45-4b4d-a229-f5efd52168ba"
      cluster-name: "Cloud Dedicated"
      cluster-type: cloud_dedicated
      admin-url: "https://admin-odin-qzx.cockroachlabs.cloud:8080"
      data-source-properties:
        url: "jdbc:postgresql://odin-qzx.aws-eu-north-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"
      api-key: "<private-key>"

    #################################################################################

    - cluster-id: "remote-insecure"
      cluster-name: "Remote Cluster (insecure)"
      cluster-type: remote_insecure
      admin-url: "http://127.0.0.1:8080"
      data-source-properties:
        url: "jdbc:postgresql://127.0.0.1:26257/defaultdb?sslmode=disable"
        username: "craig"
        password: ""

    - cluster-id: "remote-secure"
      cluster-name: "Remote Cluster (secure)"
      cluster-type: remote_secure
      admin-url: "https://127.0.0.1:443"
      data-source-properties:
        url: "jdbc:postgresql://127.0.0.1:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"

    #################################################################################

    - cluster-id: "hosted-insecure"
      cluster-name: "Hosted 3-node Cluster (insecure)"
      cluster-type: hosted_insecure
      admin-url: "http://127.0.0.1:8080"
      data-source-properties:
        url: "jdbc:postgresql://127.0.0.1:26257/defaultdb?sslmode=disable"
        username: "craig"
        password: ""
      # CockroachDB binary version for remote/hosted
      version: "v25.1.3.darwin-11.0-arm64"
#      version: "v25.1.3.darwin-11.0-amd64"
#      version: "v25.1.3.linux-amd64"
#      version: "v25.1.3.linux-arm64"

      ## (optional) List of machines/VM nodes for hosted cluster types.
      # Used to manage a cluster through pest control, potentially spanning multiple hosts as
      # opposed to many instances on local host on different ports.
      # See: https://www.cockroachlabs.com/docs/stable/cockroach-start#flags
      nodes:
        - url: http://${local-ip}:9090
          name: n1
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1a"
          advertise-addr: ${local-ip}:26257
#          listen-addr: ${local-ip}:26257
#          sql-addr: ${local-ip}:26257
          http-addr: ${local-ip}:8080
        - url: http://${local-ip}:9090
          name: n2
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1b"
          advertise-addr: ${local-ip}:26258
#          listen-addr: ${local-ip}:26258
#          sql-addr: ${local-ip}:26258
          http-addr: ${local-ip}:8081
        - url: http://${local-ip}:9090
          name: n3
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1c"
          advertise-addr: ${local-ip}:26259
#          listen-addr: ${local-ip}:26259
#          sql-addr: ${local-ip}:26259
          http-addr: ${local-ip}:8082

    #################################################################################

    - cluster-id: "hosted-secure"
      cluster-name: "Hosted 3-node Cluster (secure)"
      cluster-type: hosted_secure
      admin-url: "http://127.0.0.1:8080"
      data-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"
      ## (optional) List of machines/VM nodes for hosted cluster types.
      # Used to manage a cluster through pest control, potentially spanning multiple hosts as
      # opposed to many instances on local host on different ports.
      # See: https://www.cockroachlabs.com/docs/stable/cockroach-start#flags
      nodes:
        - url: http://${local-ip}:9090
          name: n1
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1a"
          advertise-addr: ${local-ip}:26257
#          listen-addr: ${local-ip}:26257
#          sql-addr: ${local-ip}:26257
          http-addr: ${local-ip}:8080
          secure: true
          cert-hosts: ${local-ip},${external-ip},${hostname},localhost,127.0.0.1
        - url: http://${local-ip}:9090
          name: n2
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1b"
          advertise-addr: ${local-ip}:26258
#          listen-addr: ${local-ip}:26258
#          sql-addr: ${local-ip}:26258
#          http-addr: ${local-ip}:8081
          secure: true
          cert-hosts: ${local-ip},${external-ip},${hostname},localhost,127.0.0.1
        - url: http://${local-ip}:9090
          name: n3
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1c"
          advertise-addr: ${local-ip}:25259
#          listen-addr: ${local-ip}:25259
#          sql-addr: ${local-ip}:26259
#          http-addr: ${local-ip}:8082
          secure: true
          cert-hosts: ${local-ip},${external-ip},${hostname},localhost,127.0.0.1

  # -1 denotes use of unbounded virtual threads
  threadPoolMaxSize: -1
  # Sample period for time-series data points in graphs
  samplePeriodSeconds: 300
  # Base directory for 'cluster-admin' shell script
  baseDir: "."
  # Directory for TLS certificates
  certsDir: ".certs"
  ## Other service parameters
  http:
    maxConnPerRoute: 0
    maxTotal: 0
  # Host settings for toxiproxy
  toxiproxy:
    host: localhost
    port: 8474

### Spring settings

## HTTP server parameters
server:
  port: 9090

## Profile with a truststore for SSL/TLS access to secure clusters.
# Activate this profile if you intend to sign in to a secure, self-hosted CockroachDB cluster.
# The truststore is created with the 'cluster-admin certs' command.
---
spring:
  config:
    activate:
      on-profile: ssl
  ssl:
    bundle:
      jks:
        pestcontrol:
          truststore:
            location: "file:.certs/pestcontrol.p12"
            password: "cockroach"
            type: "PKCS12"
