application:
  # Preset cluster ID (can also be set with --cluster-id XX)
  defaultClusterId: "remote-insecure"
  clusters:
    - cluster-id: "remote-insecure"
      cluster-name: "Remote 3-node Cluster (insecure)"
      cluster-type: hosted_insecure
      admin-url: "http://localhost:8080"
      data-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable"
        username: "root"
        password: ""
      version: "v25.3.1.darwin-11.0-arm64"
      secure: false
      ## List of machines/VM nodes for hosted cluster types.
      # Used to manage a cluster through pest control, potentially spanning multiple hosts as
      # opposed to many instances on local host on different ports.
      # See: https://www.cockroachlabs.com/docs/stable/cockroach-start#flags
      nodes:
        - url: http://192.168.1.10:9090
          name: n1
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1a"
          service-addr: 192.168.1.10:9090
          advertise-addr: 192.168.1.10:25257
          advertise-proxy-addr: 192.168.1.10:35257
          listen-addr: 192.168.1.10:25257
          sql-addr: 192.168.1.10:26257
          http-addr: 192.168.1.10:8080
        - url: http://192.168.1.11:9090
          name: n2
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1b"
          service-addr: 192.168.1.11:9090
          advertise-addr: 192.168.1.11:25257
          advertise-proxy-addr: 192.168.1.11:35257
          listen-addr: 192.168.1.11:25257
          sql-addr: 192.168.1.11:26257
          http-addr: 192.168.1.11:8080
        - url: http://192.168.1.11:9090
          name: n3
          locality: "region=aws-eu-central-1,zone=aws-eu-central-1c"
          service-addr: 192.168.1.12:9090
          advertise-addr: 192.168.1.12:25257
          advertise-proxy-addr: 192.168.1.12:35257
          listen-addr: 192.168.1.12:25257
          sql-addr: 192.168.1.12:26257
          http-addr: 192.168.1.12:8080
