application:
  clusters:
    - cluster-id: "test"
      cluster-name: "Test (secure)"
      cluster-type: hosted_secure
      admin-url: "http://localhost:8080"
      d1ata-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable"
        username: "craig"
        password: "cockroach"
      version: "v25.3.1.darwin-11.0-arm64"
      secure: true
      baseline:
        service-addr: localhost:9090
        listen-addr: :+25257
        advertise-addr: :+25257
        advertise-proxy-addr: :+35257
        sql-addr: :+26257
        http-addr: :+8080
        cert-hosts: ${local-ip},${external-ip},${hostname},localhost,127.0.0.1
      nodes:
        - locality: "region=eu-central-1,zone=eu-central-1a"
        - locality: "region=eu-central-1,zone=eu-central-1b"
        - locality: "region=eu-central-1,zone=eu-central-1c"
