###############################################################################################################
# Pest Control Application Configuration
#
# This file overrides the default application configuration properties (src/main/resources/application.yml).
# See https://docs.spring.io/spring-boot/appendix/application-properties/index.html for all spring boot
# properties and src/main/resources/application.yml for application defaults.
###############################################################################################################
application:
  # Preset cluster ID
  defaultClusterId: "local-insecure"
  ## List of pre-configured CockroachDB clusters
  clusters:
    - cluster-id: "local-insecure"
      cluster-name: "Local Cluster (insecure)"
      cluster-type: hosted_insecure
      admin-url: "http://localhost:8080"
      data-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable"
        username: "craig"
        password: ""
      version: "v25.3.1.darwin-11.0-arm64"
      #      version: "v25.3.1.darwin-11.0-amd64"
      #      version: "v25.3.1.linux-amd64"
      #      version: "v25.3.1.linux-arm64"
      baseline:
        service-addr: localhost:9090
        advertise-addr: localhost:+25257
        advertise-proxy-addr: localhost:+35257
        listen-addr: localhost:+25257
        sql-addr: localhost:+26257
        http-addr: localhost:+8080
      nodes:
        - locality: "region=eu-central-1,zone=eu-central-1a"
        - locality: "region=eu-central-1,zone=eu-central-1b"
        - locality: "region=eu-central-1,zone=eu-central-1c"
        - locality: "region=eu-west-1,zone=eu-west-1a"
        - locality: "region=eu-west-1,zone=eu-west-1b"
        - locality: "region=eu-west-1,zone=eu-west-1c"
        - locality: "region=eu-west-2,zone=eu-west-2a"
        - locality: "region=eu-west-2,zone=eu-west-2b"
        - locality: "region=eu-west-2,zone=eu-west-2c"
        - locality: "region=eu-north-1,zone=eu-north-1a"
        - locality: "region=eu-north-1,zone=eu-north-1b"
        - locality: "region=eu-north-1,zone=eu-north-1c"

    - cluster-id: "local-secure"
      cluster-name: "Local Cluster (secure)"
      cluster-type: hosted_secure
      admin-url: "https://localhost:8080"
      data-source-properties:
        url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"
      version: "v25.3.1.darwin-11.0-arm64"
      baseline:
        service-addr: localhost:9090
        advertise-addr: localhost:+25257
        advertise-proxy-addr: localhost:+35257
        listen-addr: localhost:+25257
        sql-addr: localhost:+26257
        http-addr: localhost:+8080
        cert-hosts: ${local-ip},${external-ip},${hostname},localhost,127.0.0.1
      nodes:
        - locality: "region=eu-central-1,zone=eu-central-1a"
        - locality: "region=eu-central-1,zone=eu-central-1b"
        - locality: "region=eu-central-1,zone=eu-central-1c"
        - locality: "region=eu-west-1,zone=eu-west-1a"
        - locality: "region=eu-west-1,zone=eu-west-1b"
        - locality: "region=eu-west-1,zone=eu-west-1c"
        - locality: "region=eu-west-2,zone=eu-west-2a"
        - locality: "region=eu-west-2,zone=eu-west-2b"
        - locality: "region=eu-west-2,zone=eu-west-2c"
        - locality: "region=eu-north-1,zone=eu-north-1a"
        - locality: "region=eu-north-1,zone=eu-north-1b"
        - locality: "region=eu-north-1,zone=eu-north-1c"

    - cluster-id: "97a73235-fa45-4b4d-a229-f5efd52168ba"
      cluster-name: "Cloud Dedicated"
      cluster-type: cloud_dedicated
      admin-url: "https://admin-<name>.cockroachlabs.cloud:8080"
      api-key: "<cc-private-key>"
      data-source-properties:
        url: "jdbc:postgresql://odin-<name>.cockroachlabs.cloud:26257/defaultdb?sslmode=require"
        username: "craig"
        password: "cockroach"
